server:
  port: 3344
  
spring:
  application:
    name: cloud-config-server
  cloud: 
    config: 
      server: 
        git:
          uri: https://github.com/HUT-Eleven/SpringCloudConfig.git    #github仓库的位置
          
