server:
  port: 9527
  
spring:
  application:
    name: microservicecloud-zuul-gateway
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
  instance:
    instance-id: gateway_9527
    prefer-ip-address: true
    
zuul: 
  prefix: /hut                  #设置统一的公共前缀
  ignored-services: 
#    microservicecloud-dept     #隐藏单个
    "*"                         #隐藏所有
  routes: 
    mydept.serviceId: microservicecloud-dept  #微服务的name-spring.application.name
    mydept.path: /mydept/**                   #映射后的路径
